### ISSUE TITLE
Optifine files being removed

### ISSUE THREAD

**Issue by Patbox** [ComunidadAylas/PackSquash#1]
I've tested PackSquash and it looks like it removes Optifine .properties files. It can breaks some pack, so it needs to be fixed.

**Comment by AlexTMjugador** [comment]
Thanks for the feedback! Do you know if Optifine adds other types of files to the resource packs, too? Is the properties file format similar to [this one](https://minecraft.gamepedia.com/Server.properties)?

**Comment by Patbox** [comment]
I remember that there's few. They should be described here https://github.com/sp614x/optifine/tree/master/OptiFineDoc/doc

**Comment by AlexTMjugador** [comment]
Thank you, that was useful! As far as I know, OptiFine only adds property files to the resource packs, so PackSquash only needs to support those to work as you'd expect.

I've recently pushed a commit that adds support for resource pack files added by mods like OptiFine. I've decided that the support has to be enabled manually with the "-m" option in the command line, so that PackSquash doesn't inadvertently include "junk" files for people that don't use mods. Please grab the latest executables from here and let me know if the changes work fine for you: https://github.com/ComunidadAylas/PackSquash/actions/runs/141137798

**Comment by AlexTMjugador** [comment]
Some people tested the new build and you reacted with a thumbs up to my previous comment, so I assume that the changes are fine and consider this issue resolved. Don't hesitate proving me wrong :)
