### ISSUE TITLE
Decode?

### ISSUE THREAD

**Issue by Grummiom** [ComunidadAylas/PackSquash#191]
### Related problem or need

is there a way to decode protected resource pack?
i accidently deleted my main resource pack file and i only have the protected one
is there anyway to redo

### Proposed solution

add a future to decoding RPs

### Alternative solutions

add something like a key file or key number so the owner can input the key and it will decode rp

**Comment by AlexTMjugador** [comment]
PackSquash does not expose any functionality to extract the protected ZIP files it generates, I'm afraid. Moreover, I have reservations for adding such a feature due to security concerns.

In principle, I wouldn't mind decoding packs on a case-by-case basis to help with data loss circumstances like this. However, doing so requires me to judge whether people are honest and have reasonable motives, because I don't want to enable nefarious activities. I'm not sure how I should do that, so I prefer to err on the side of caution by not decoding packs, sorry.

You may have success recovering most of your pack with standard data recovery tools if the filesystem you had the pack stored in has been seldom written to since you deleted it, but this is an advanced task.
