### ISSUE TITLE
CLI argument to provide a count of files that will be squashed with the given config

### ISSUE THREAD

**Issue by DeflatedPickle** [ComunidadAylas/PackSquash#23]
**Is your feature request related to a problem? Please describe.**
In Quiver, the progress monitor for the PackSquash export step assumes that every file in a pack has the potential to be squashed and so could give an inaccurate total

**Describe the solution you'd like**
I would like to have an argument that could be passed to the CLI that would return the total files that will be changed given the current config

Example (the flag `-t` could also be `--total`);
```
> packsquash -t -- config.toml
31
```

**Describe alternatives you've considered**
It's possible that I could write a config guesser into Quiver but it'd be nice if one shipped with PackSquash

**Additional context**
If a user had a config that didn't change audio files, this wouldn't be reflected by the progress monitor and it would likely hang

**Comment by AlexTMjugador** [comment]
To be honest, I've been thinking a lot lately on offering a better API for third-party applications that use PackSquash, in C (because every language FFI I know of at least allows calling C) and in JVM languages via [JNI](https://docs.rs/jni/0.19.0/jni/). This would allow for much richer communication between both components, including the one you request, and maybe allow for additional use cases I'm not thinking on (although, of course, the current method of interfacing with PackSquash will not be deprecated). The main "downside" I can see for this is that it requires refactoring quite a bit of things about how PackSquash code is organized internally, because right now there are a lot of responsibilities crammed into a file, and when writing it I didn't think it'd even be mildly successful, to be honest... ;). I've already started with that pain in the [`wip`](https://github.com/ComunidadAylas/PackSquash/tree/wip) branch, which contains code that eventually will be merged back into `master` for v0.3.0. However, v0.3.0 is arguably the biggest PackSquash update ever, and I'm not sure whether I'll be comfortable delaying it more to polish a public API. It already is taking pretty long, because changes like supporting reusing the unchanged files that were compressed in a previous run of PackSquash require quite a bit of thought to be compatible with all the feature set that PackSquash offers, especially non-strict ZIP spec compliance mode, and unfortunately I've a lot of other things to do.

Moving down to Earth, even if the user specifies that sound files should just be copied, PackSquash prints a message anyway, so the progress count shouldn't break because of this reason:

https://github.com/ComunidadAylas/PackSquash/blob/cd65ece9f0c3973d0fe08e85f519a5bb1f03a297/src/resource_pack_file.rs#L631-L639

However, PackSquash won't output what it considers to be system and hidden files depending on the value of the corresponding setting, so there's a potential gotcha there, and I agree with you that parsing PackSquash config in Quiver is ugly.

In general, would you prefer to wait for a nice JNI API to use for PackSquash, or instead carry on with command line switches like this, which may be easier to implement for me, but definitely less elegant in the long term?

**Comment by DeflatedPickle** [comment]
I personally think that a CLI is the best contender for most project interfaces as the binary program can be switched out as long as the CLI is the same, so if there was a bug discovered in PackSquash or a new release, users wouldn't need to wait for me to ship a hotfix. Also since PackSquash has its config, it doesn't seem to me like extra time needs to be used up writing an API and wrappers and probably wouldn't use one if it existed instead of the CLI

**Comment by AlexTMjugador** [comment]
I was thinking of offering that API from a shared library (.dll file on Windows, .so file on Unix-like OSes). Shared libraries can also be replaced if its exported symbols (i.e. public functions) do not change in a backwards incompatible manner, so with proper versioning that shouldn't be a concern either. However, it's relieving to see that a CLI works fine for your needs, so I can focus the v0.3.0 on more user-facing improvements :)

Anyway, to solve the issue at hand, I think it'd be satisfactory for PackSquash to just be more verbose about the operations it does, printing more status info (including the one you request), maybe behind a `-v` switch. However, PackSquash uses directory scanning APIs that return an iterator, which means that PackSquash actually doesn't know the files it will process before iterating over them, and therefore it can't print a total count before starting. It is possible to scan the directory twice, but this is not very efficient and, more importantly, opens the possibility for race conditions (i.e. another program adds or removes files after the first scan is complete, so the total that was computed on that first scan becomes incorrect). Have you considered other alternatives? Namely, would it be acceptable for your use case to treat the number of files in a directory just as a hint of the work that will be done, and considering the work done when PackSquash exits successfully, instead of when a certain number of files was processed?

**Comment by DeflatedPickle** [comment]
> Shared libraries can also be replaced
You're right there. Silly me

> However, PackSquash uses directory scanning APIs that return an iterator, which means that PackSquash actually doesn't know the files it will process before iterating over them
Is it not possible to get what the iterator will iterate from the iterator? If not from before running it, there could be a simple `hasCounted` that is checked - if false and the user wants the file count, prints the list of the iterator contents

> It is possible to scan the directory twice, but this is not very efficient
My original idea, before submitting the issue, was to have the flag as a different mode for PackSquash that would just print the file count

> Have you considered other alternatives?
The first alternative that comes to mind is using the indeterminate mode of progress bars. However, as I'm using an unedited Swing `ProgressMonitor`, due to this [embarrassingly easy issue](https://bugs.openjdk.java.net/browse/JDK-4448318) never getting resolved, that simply isn't possible. Maybe I could extend it or straight up copy and edit the class?

> Namely, would it be acceptable for your use case to treat the number of files in a directory just as a hint of the work that will be done
I believe it already [does this](https://github.com/DeflatedPickle/Quiver/blob/b16b667df9ad0ab1192393a50bc550aa487b10cf/packsquashstep/src/main/kotlin/com/deflatedpickle/quiver/packsquashstep/PackSquashStep.kt#L103), as it closes the dialog after every line from the PackSquash output has been iterated. This is fine unless there's ever a situation where PackSquash finishes and the progress bar has only gotten halfway and the dialog closes. Not a massive problem either, but it seems like something someone could notice and spend a few hours reading their logs and Quiver's code to find out if there was a problem

> would you appreciate PackSquash printing some other kind of info?
I'm not sure what other information it could provide that I don't have access to already

**Comment by AlexTMjugador** [comment]
> Is it not possible to get what the iterator will iterate from the iterator? If not from before running it, there could be a simple `hasCounted` that is checked - if false and the user wants the file count, prints the list of the iterator contents

Conceptually, an iterator does not contain a collection of elements; it just holds the state needed to know what element should come next (which usually is a index, a pointer, or something like that). Printing the iterator object contents will not show any elements. So, to get a file count or a file list, you need to iterate over the iterator, but when you do so, you consume it: it is not possible rewind it back to the first yielded file to do the actual work.

It is possible to convert the iterator to a list, and then ditch the iterator in favor of the list, which does not pose race conditions, because the directory is still scanned once, and would allow printing a total count efficiently. However, that implies storing data of the files of an entire directory and subdirectories in memory, which can be thousands for bigger resource packs, and I'm not very comfortable with that (each file takes 280 bytes for the dirent structure on my Linux x64 machine + a root file path buffer that may be as big as the user wants to, but let's say it's another 128 bytes + probably several extra fields and memory alignment padding I'm not aware of; let's say they take 64 bytes = 472 bytes of memory per file. Multiply it by 2000 and you get that this list would take ~922 KiB, which is not that much nowadays, but still puts pressure on the CPU data caches).

> My original idea, before submitting the issue, was to have the flag as a different mode for PackSquash that would just print the file count

Sadly, it is not possible, in general, to guarantee that between runs of PackSquash the file count remains the same. It may happen that a user or another program creates or deletes files in-between the executions. For Quiver, I think you copy the files to a unique temporary folder, so this race condition scenario would seem more unlikely, but there still is nothing that forbids the user or another application from messing with that directory (like antivirus software, for example). File locks exist for these purposes, but they are platform-dependent and sometimes advisory at best, so they can't be relied upon either.

Bottom line, the way I see it, PackSquash could either:

- Have a special mode that prints the file count and does nothing else efficiently and correctly, but this can introduce race conditions in programs that rely on this count being accurate.
- Print the file count and do its work by iterating the directory twice, which is prone to race conditions too.
- Print the file count and do its work by converting the iterator to a list, which is correct, but not efficient (more memory usage).

None of these approaches sound ideal to me, but I'm open to ideas that sound better, of course.

> The first alternative that comes to mind is using the indeterminate mode of progress bars. However, as I'm using an unedited Swing `ProgressMonitor`, due to this [embarrassingly easy issue](https://bugs.openjdk.java.net/browse/JDK-4448318) never getting resolved, that simply isn't possible. Maybe I could extend it or straight up copy and edit the class?

That could work, but if you end up straight copying and editing the class, I'd rather make PackSquash use ~922 KiB more of memory... I don't want that maintenance burden for you either :)

> > Namely, would it be acceptable for your use case to treat the number of files in a directory just as a hint of the work that will be done
> 
> I believe it already [does this](https://github.com/DeflatedPickle/Quiver/blob/b16b667df9ad0ab1192393a50bc550aa487b10cf/packsquashstep/src/main/kotlin/com/deflatedpickle/quiver/packsquashstep/PackSquashStep.kt#L103), as it closes the dialog after every line from the PackSquash output has been iterated. This is fine unless there's ever a situation where PackSquash finishes and the progress bar has only gotten halfway and the dialog closes. Not a massive problem either, but it seems like something someone could notice and spend a few hours reading their logs and Quiver's code to find out if there was a problem

I wonder if it would be fine that, in case the progress bar does not reach 100% before PackSquash exits successfully, it temporarily ramps up to 100%, and then the window closes, after a bit of time? That way the user would always see the progress bar reach completion, which is good UI feedback. If this is viable, and you don't have any more use cases for this total file count, then I think this would be the most efficient solution I can came up with.

> > would you appreciate PackSquash printing some other kind of info?
> 
> I'm not sure what other information it could provide that I don't have access to already

Perfect!

**Comment by DeflatedPickle** [comment]
> It is possible to convert the iterator to a list, and then ditch the iterator in favor of the list

With the explanation you've given, this doesn't seem like a reasonable change to make

> None of these approaches sound ideal to me, but I'm open to ideas that sound better, of course.

As any approach would introduce race conditions, it seems like they would only serve to harm PackSquash stability. Since the feature would only really be applicable for me, it seems best to leave it out

> I don't want that maintenance burden for you either

It wouldn't be a problem, really. I already maintain enough so I'm not bothered with a bit more. But it's likely that I wouldn't have to copy it if I made use of a mixin or reflection

> I wonder if it would be fine that, in case the progress bar does not reach 100% before PackSquash exits successfully, it temporarily ramps up to 100%

So, I never claim that I'm a smart person. I frequently claim the exact opposite and situations like this are exactly why. I can certainly do this and I can't believe I didn't think of it. It's so simple!

I'll close this now but if I happen to run into anything related to this, I'll come back with a comment

**Comment by AlexTMjugador** [comment]
Two heads are better than one. Don't hesitate getting back in touch! :+1:
