### ISSUE TITLE
Data packs support for 1.21

### ISSUE THREAD

**Issue by lottuce-yami** [ComunidadAylas/PackSquash#327]
### Distribution

Windows executable

### Bug description

In 1.21 version of Minecraft, various folders in the data pack structure were renamed - [source (Minecraft Wiki)](https://minecraft.wiki/w/Data_pack#History). However, PackSquash simply skips files in those folders and makes the data pack unusable.

### Reproduction steps

1. Create a data pack with, for example, `.mcfunction` files in the `data/*/function/`.
2. Try to optimize the pack with PackSquash.

### Expected behavior

Files from the renamed folders should get copied to the target pack.

### Attached files

Example 1.21 data pack - [example.zip](https://github.com/user-attachments/files/16946035/example.zip)

### Additional context

The program can check for the pack version and use different paths if the version is `48` [(source)](https://minecraft.wiki/w/Data_pack#Pack_format) or higher.

**Comment by AlexTMjugador** [comment]
Thanks for the report and the Minecraft wiki changelog link. 1.21 did indeed change the directory layout of datapacks a bit, causing the problems you describe. I'll eventually fix this.

**Comment by AlexTMjugador** [comment]
The commit that closed this issue should fix the reported problem! If anyone's interested, please feel try out the latest unstable builds and let us know how the fix works for you. This fix is expected to make it to the next stable release, but such stable release was not published yet, so that's why unstable builds should be used to test it for now.
