### ISSUE TITLE
MC 1.17 core shaders error on processing

### ISSUE THREAD

**Issue by pau101** [ComunidadAylas/PackSquash#34]
**Describe the bug**
MC 1.17 "core" shaders using `#moj_import` preprocessing directives error when processing:
```
! assets/minecraft/shaders/core/rendertype_text.fsh: Shader parse error: error: 0: at line 3, in Tag:
#moj_import <fog.glsl>
 ^

1: at line 3, in Alt:
#moj_import <fog.glsl>
 ^
```

**To Reproduce**
Create a pack containing a fragment shader such as `assets/minecraft/shaders/core/rendertype_text.fsh`:
```glsl
#version 150

#moj_import <fog.glsl>

uniform sampler2D Sampler0;

uniform vec4 ColorModulator;
uniform float FogStart;
uniform float FogEnd;
uniform vec4 FogColor;

in float vertexDistance;
in vec4 vertexColor;
in vec2 texCoord0;

out vec4 fragColor;

void main() {
    vec4 color = texture(Sampler0, texCoord0) * vertexColor * ColorModulator;
    if (color.a < 0.1) {
        discard;
    }
    fragColor = linear_fog(color, vertexDistance, FogStart, FogEnd, FogColor);
}
```

**Expected behavior**
The file to be processed and packsquash to finish successfully.

**Comment by AlexTMjugador** [comment]
Thank you very much for reporting this issue! Its cause is that PackSquash uses a standards-compliant GLSL parser that does not recognize this custom extension made by Mojang.

I'm investigating a proper fix to it. It will be part of the final v0.3.0 release.

**Comment by AlexTMjugador** [comment]
A fix for this issue was made in commit https://github.com/ComunidadAylas/PackSquash/commit/ab848ae2db1a02fc5a5de7d5227e6f49856fcb74. This commit will be part of the final v0.3.0 release, but until that happens, builds that contain this fix are available as [GitHub Actions artifacts](https://github.com/ComunidadAylas/PackSquash/actions/runs/1106358110). This fix was also rolled out to the APT repository, as it doesn't contain a pristine v0.3.0-rc.1 build anyway.

Basically, the fix exchanged `#include` preprocessor directive support, which was non-standard and not well supported by Minecraft anyway, for `#moj_import`. This means that files with a `#include` directive will be rejected, because such directives should be substituted by `#moj_import`.

I think it's interesting to note that the GLSL preprocessor introduced in 1.17 is a bit more strict parsing preprocessor directives than the PackSquash parser. The parser used by PackSquash supports more filler characters between preprocessor directive elements, like newline escapes, so it could happen that a shader file accepted by PackSquash is rejected by Minecraft later. However, this shouldn't matter in practical scenarios for several reasons:

- The extra filler characters accepted by the PackSquash parser are extremely rare to see in practice.
- I may be unable to make it stricter without breaking compatibility with older versions that didn't use a custom preprocessor, although I didn't look into this reason enough to confirm it.
- I'd say that the preprocessor used by PackSquash, or the Minecraft GLSL parser, depart from very strict standards compliance, so there probably are more ways for this "PackSquash accepts the shader but Minecraft rejects it" scenario to happen anyway.

In the strange case that someone is that curious, this is the Java regular expression that Minecraft 1.17.1 uses to parse this preprocessor directive:

`(#(?:/\\*(?:[^*]|\\*+[^*/])*\\*+/|\\h)*moj_import(?:/\\*(?:[^*]|\\*+[^*/])*\\*+/|\\h)*(?:\"(.*)\"|<(.*)>))`

Please confirm whether the fix works out for you, and if so we can close the issue. Thanks again!

**Comment by pau101** [comment]
Yep it resolved it, thanks!
