### ISSUE TITLE
Consider making a pterodactyl egg.

### ISSUE THREAD

**Issue by tankinnwow** [ComunidadAylas/PackSquash#38]
Have you considered making and egg for the Pterodactyl Panel. It would be super nice to have.  Since the panel uses docker you could configure the container to work however you needed. I am not an expert at these things so it took a bit of work to setup PackSquash.

I tried making one myself but failed spectacularly, way above my head.

**Comment by AlexTMjugador** [comment]
I have never considered making such a thing, but I agree that it can be useful to automate server resource pack optimization or make it easier, after reading the Pterodactyl documentation for a bit.

As Pterodactyl uses Docker to run the server components, I think that an egg could take some inspiration from the already existing GitHub Action for PackSquash, which also runs on a Docker container and allows optimizing packs in a GitHub Actions workflow easily: https://github.com/ComunidadAylas/PackSquash-action. At the very least, the action is an example on how PackSquash can be run in a Docker container and integrated with an already existing workflow, and in the best case scenario it can be useful to get started with implementing this enhancement.

I'm adding this to the roadmap, but without assigning it to any release. Feel free to continue working on this, and if we both want, we can make this egg official, as it was done with the action. Thanks!

**Comment by tankinnwow** [comment]
Thanks for the positive reply. I will try to make it work on my end and i will let you know if i manage to cobble something together. No promises since i suck at this stuff :)

**Comment by Danieljunek17** [comment]
I am someone that makes private pterodactyl eggs but I would not recommend to make this egg because of 2 big criteria

1. Complication to use the egg
2. the way you can use eggs as a hosting

basically the first "issue" basically resolves around the fact that it is as difficult to use it inside pterodactyl as inside github and settings up the action and the second thing is basically you can't use It unless you are the panel admin because hosting company's won't be interested in making this tool publicly available unless someone also makes a big panel modification so users can use this for free while deleting all servers (docker containers) after each process of using it and letting them create them so this is not a nice addition for 99% of people unless other additions are done as well

**Comment by AlexTMjugador** [comment]
I don't think that the PackSquash GitHub action is particularly difficult to use. In fact, its defaults are so sensible that usually you barely need to bother with settings and their format, unlike when running PackSquash yourself. If the Pterodactyl egg has a similar use "difficulty" I'd be satisfied.

About the hosting angle, I get that indeed some cooperation is necessary to make a PackSquash egg available for those that use the Pterodactyl services of a hosting provider, instead of running Pterodactyl themselves. On my end, I'm open to discuss improvements on how PackSquash can behave better for this use case. On the hosting provider end, I digress that they won't have any interest in the egg: some server owners already find PackSquash pretty useful, and offering a convenient way to use it would be part of the value proposition of that provider, which may attract new customers and create a competitive advantage.

**Comment by AlexTMjugador** [comment]
Some news that may be relevant for this enhancement: PR #111 was just merged, and it did the necessary ground work to build and publish official PackSquash Docker images as a part of the CI workflow.

**Comment by AlexTMjugador** [comment]
@xMikux and I were able to discuss and research this a few hours ago by [cobbling together a simple PackSquash Pterodactyl egg](https://github.com/Docker-Collection/docker-packsquash-egg). Based on our experience with the egg, we came to the conclusion that, while it is technically possible to develop a PackSquash Pterodactyl egg, it would indeed be quite inconvenient to use, and we decided against making an official one.

Pterodactyl eggs are meant to define how to execute persistent server applications, which PackSquash is not. In their default configuration, Pterodactyl nodes restart the containers defined by eggs when they finish, which is inappropriate for PackSquash, and changing this requires dedicating a separate node. In addition, end users have no control over which eggs they can deploy on which nodes in the game server hosting scenarios we can imagine, and we don't think that hosting providers would benefit more from integrating PackSquash with an egg than with other already existing means, such as deploying images with built-in PackSquash executables (Daniel mentioned this scenario in their comment above, but I understand it better now thanks to this experience). And this does not even address how to get the necessary inter-container communication, which is highly dependent on the particular environment.

All in all, I'm grateful for the suggestion and comments. Big props to @xMikux for the example egg, and also for the insightful discussion we had, which brought up interesting ideas on how to better integrate PackSquash into beginner-friendly game server hosting scenarios!
