### ISSUE TITLE
Allow .txt inclusion.

### ISSUE THREAD

**Issue by MinecraftAdmin** [ComunidadAylas/PackSquash#40]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Allow *.txt to be included in final archive.

**Describe alternatives you've considered**
None.

**Additional context**
I would like to add info txt files to various subdirectories, but cannot at the moment as PackSquash excludes them from archive process. Just a simple .txt inclusion option would suffice.

Thank you!

**Comment by AlexTMjugador** [comment]
I have observed this pattern of including .txt files with licensing and other kinds of information in some public resource packs I used for testing PackSquash, and I was curious if people really wanted to leave such files in the pack. With this issue I can definitely see that there could be some real demand for this improvement, so thank you for this.

However, while I understand the need of storing some additional metadata not used by Minecraft in the pack for several purposes, I'm not sure that adding text files is the best way to do it. In my opinion, there are several reasons why they are a not so good solution:

- Storing a file in a ZIP file incurs in some space overhead. In other words, it's more space efficient to have a single big file than many smaller ones.
- Raw text files are not easy to parse by machines, which can make things harder when developing or using software to automatically process packs, besides PackSquash.
- Such text files are not standard in any way, either. Some packs have them, some not. Of those that have these additional files, not all of them choose to store them in a consistent location. I've seen these files being stored in the root directory, in related subdirectories, and almost wherever you can imagine. Neither a program or an end user wouldn't really know where to look at for these additional bits of information, unless they look somewhat exhaustively.

Instead, I think the best approach would be to store this kind of metadata in the `pack.mcmeta` file, using additional keys with a prefix that Mojang will very likely never use. I like this approach more because it tackles the previously mentioned downsides satisfactorily:

- Any valid pack has a `pack.mcmeta` file, so there is no space overhead for storing any additional files.
- `pack.mcmeta` is guaranteed to be valid JSON in a well-formed pack, and JSON is easy for computers to parse. PackSquash can also already optimize JSON.
- The `pack.mcmeta` file is already expected to contain pack metadata, like its name, format version and description. Adding additional fields to it feels natural, and it is a place where people would instinctively look for this kind of information. Moreover, the Minecraft community can develop a standard on what additional JSON keys to use for what purposes and with what values, making these keys machine parseable and consistent. This could also allow for rich text, links and other features that are not practical to achieve with just raw text files, too. If this hypothetical standard is well designed and gains enough traction, Mojang likely will notice it and not try to break it in future Minecraft updates unless they have a very good reason.

So, considering the previously exposed points, do you agree that using additional keys in the `pack.mcmeta` file would be a better solution for you? Do you think that raw text files have some advantage I didn't think about, apart from the trivial one of "people already use .txt files and I wanted to do that too", or an use case that is not fulfilled by the `pack.mcmeta` approach? Let me know your thoughts about this!

**Comment by MinecraftAdmin** [comment]
Text files can be used to store licensing information and also to inform resource pack "remixers" of the origins of the pack they're manipulating. 

Using the robust options system of PackSquash, maybe an option along the lines of "TXT_File_Exclusion" can be added, which can default to "true" to keep space overhead low, and make the pack as scaleable as possible for those who wish to retain the current handling of non-native Minecraft resources.

Although I am all for openness of sharing the wealth of content stored in resource packs, for most beginners to be made aware of the origins of the content and appropriate licensing, the widely compatible TXT file is easier to view in a text editor than an mcmeta file, which may not have the correct association on the system of the pack viewer.

Furthermore, miscellaneous pack information (such as origins, licensing etc) are better suited for non mcmeta files as they can be easily accessed and viewed outside the Minecraft client, which is how I believe licensing and documentation should be, as accessible as possible. 

I appreciate you looking into this.

**Comment by AlexTMjugador** [comment]
While I still think that using the `pack.mcmeta` file in some way could be more appropriate for storing certain kinds of metadata, I find your points about ease of viewing and beginner-friendliness pretty compelling too. After all, I agree that the JSON format is not the best one to write things like multi-line licensing information in a way that's nice to read within a text editor due to the facts that you've exposed, and that JSON strings shouldn't contain control characters without escaping, like line breaks. Going forward, I think that some standardized combination of text files and metadata keys in the `pack.mcmeta` file could bring the best of both worlds.

However, developing such a standard is not in scope for PackSquash, and after some more thought I find it fair to add an additional option to copy the files to the generated ZIP files that it would otherwise exclude. This would also help future-proofing PackSquash in case Mojang adds new types of files to packs, so people don't need to wait for me to add support for those files in order to continue using the software (obviously, of course, proper file-specific support would very likely achieve better compression and/or protection than just copying things around, so it wouldn't be desirable for such an option to be a permanent "fix"). It would also be compatible with an hypothetical future addition to support the standard I've been describing, and in general bring more control to pack authors about what files are included in their pack, which is a good thing.

So, all in all, I'm adding this to the roadmap, scheduling it for the next release. Thank you again for bringing this issue to my attention!
