### ISSUE TITLE
Supports .mcfunction optimization

### ISSUE THREAD

**Issue by sya-ri** [ComunidadAylas/PackSquash#67]
### Easy way
- Delete empty lines
- Delete comments

### Difficult way
- Replace with a shorter command with the same behavior (but it is version dependent and does advanced processing)
- Merge multiple files (but it needs to find out if they can be merged)

**Comment by AlexTMjugador** [comment]
This issue has been on the roadmap for a bit of time now, but it's okay to create an issue for it anyway!

I've some notes about how exactly these files are parsed in a Google Docs document, made after reading Minecraft code. It also is easy to validate that slashes are not used to begin commands (recent versions of Minecraft reject them, at least). If you are interested on working on this I can share those details with you :heart:

On a side note, for those end users reading this issue, I think it's worth mentioning that PackSquash already recognizes .mcfunction files and copies them appropriately. The enhancement at hand is doing some actual format-specific optimization and validation to them too, instead of just only copying them over as it's done currently.

**Comment by sya-ri** [comment]
Yes! I'm interested in working on this <3 Could you share the details?

**Comment by AlexTMjugador** [comment]
Sure! Shared over Discord :smile:
