### ISSUE TITLE
Packsquash throws errors about dlls not being installed when gstream is repaired, and set in the user's path variables.

### ISSUE THREAD

**Issue by GreedySoap** [ComunidadAylas/PackSquash#93]
Heyo! As said in the title, I've followed the wiki on how to setup packsquash, however even after installing, repairing, and uninstalling (ofc reinstalling after) gstreamer, nothing seems to work, and it still spits out that error. 

![image](https://user-images.githubusercontent.com/52713156/161910609-bd225126-008a-4cfb-860c-83ad0d680d35.png)

**Comment by AlexTMjugador** [comment]
Hey! :wave:

This is a rather unfortunate situation, as after following the installation guide on a GStreamer-free Windows installation other users and myself are able to use it with no problems.

The step 4 of the Windows installation instructions is really important for this error to not appear though, as otherwise Windows does not know where to find the GStreamer libraries that PackSquash needs to function. Have you double-checked that you have modified the `Path` variable?

If you continue having trouble installing PackSquash, please consider joining our Discord server, to keep the issue tracker free of troubleshooting comments and receive quicker support.
